# Generated by Django 4.2.2 on 2023-11-02 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='runner',
            old_name='middle_name',
            new_name='club',
        ),
    ]
