# Generated by Django 4.2.2 on 2024-11-02 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("races", "0006_alter_result_options_race_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="race",
            name="season_start_year",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
