# Generated by Django 4.2.2 on 2025-01-13 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("races", "0009_alter_race_slug"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="runner",
            unique_together={("first_name", "last_name")},
        ),
    ]
