# Generated by Django 4.2.2 on 2025-11-02 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0010_alter_runner_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_start_year', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='runner',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='runner',
            name='season',
            field=models.ForeignKey(default=24, on_delete=django.db.models.deletion.RESTRICT, to='races.season'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='runner',
            unique_together={('first_name', 'last_name', 'season')},
        ),
    ]
