# Generated by Django 4.2.2 on 2025-11-05 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("races", "0012_alter_season_season_start_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="runner",
            name="season",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="races.season"
            ),
        ),
    ]
