# Generated by Django 4.2.2 on 2025-11-05 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("races", "0013_alter_runner_season"),
    ]

    operations = [
        migrations.AddField(
            model_name="race",
            name="season",
            field=models.ForeignKey(
                default=2025,
                on_delete=django.db.models.deletion.CASCADE,
                to="races.season",
            ),
            preserve_default=False,
        ),
    ]
