# Generated by Django 4.2.2 on 2023-07-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='race_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
