# Generated by Django 4.2.2 on 2023-06-24 23:32

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0002_remove_race_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='location',
            field=location_field.models.plain.PlainLocationField(default='55.82,-4.26', max_length=63),
        ),
    ]
