# Generated by Django 4.2.2 on 2023-07-17 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0004_remove_result_position_result_category_position_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('points', models.PositiveIntegerField(blank=True, null=True)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='races.result')),
            ],
            options={
                'ordering': ['result__race__race_number', 'version'],
            },
        ),
        migrations.DeleteModel(
            name='ResultWithPoints',
        ),
    ]
