# Generated by Django 4.2.2 on 2023-07-19 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0005_resultversion_delete_resultwithpoints'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultversion',
            old_name='points',
            new_name='category_points',
        ),
        migrations.AddField(
            model_name='resultversion',
            name='gender_points',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resultversion',
            name='general_points',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
