# Generated by Django 4.2.2 on 2023-07-20 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0007_raceversion_resultversion_race_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='races.race')),
            ],
            options={
                'ordering': ['race', 'version_number'],
                'unique_together': {('race', 'version_number')},
            },
        ),
        migrations.AlterModelOptions(
            name='resultversion',
            options={'ordering': ['general_points']},
        ),
        migrations.CreateModel(
            name='ClassificationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general_points', models.PositiveIntegerField(blank=True, null=True)),
                ('gender_points', models.PositiveIntegerField(blank=True, null=True)),
                ('category_points', models.PositiveIntegerField(blank=True, null=True)),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classification_results', to='races.classification')),
                ('runner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classification_results', to='races.runner')),
            ],
            options={
                'ordering': ['-general_points'],
            },
        ),
    ]
