# Generated by Django 4.2.2 on 2023-08-27 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0008_classification_alter_resultversion_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultversion',
            name='race_version',
        ),
        migrations.RemoveField(
            model_name='resultversion',
            name='result',
        ),
        migrations.AlterModelOptions(
            name='classificationresult',
            options={'ordering': ['general_points']},
        ),
        migrations.DeleteModel(
            name='RaceVersion',
        ),
        migrations.DeleteModel(
            name='ResultVersion',
        ),
    ]
