# Generated by Django 4.2.2 on 2023-07-01 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0010_rename_runners_result_runner'),
    ]

    operations = [
        migrations.AddField(
            model_name='runner',
            name='middle_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
