# Generated by Django 4.2.2 on 2023-07-01 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0011_runner_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='runner',
            name='category',
            field=models.CharField(choices=[('MS', 'MS'), ('FS', 'FS'), ('M40', 'M40'), ('F40', 'F40'), ('M50', 'M50'), ('F50', 'F50'), ('M60', 'M60'), ('F60', 'F60'), ('M70', 'M70'), ('F70', 'F70'), ('M80', 'M80'), ('F80', 'F80')], max_length=3, null=True),
        ),
    ]
