# Generated by Django 4.2.2 on 2023-07-04 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0012_runner_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='race_file',
            field=models.FileField(blank=True, null=True, upload_to='races/%Y/%m/%d/'),
        ),
    ]
