# Generated by Django 4.2.2 on 2023-09-18 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("races", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Classification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_number", models.PositiveIntegerField()),
                (
                    "race",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classifications",
                        to="races.race",
                    ),
                ),
            ],
            options={
                "ordering": ["race", "version_number"],
                "unique_together": {("race", "version_number")},
            },
        ),
        migrations.CreateModel(
            name="ClassificationResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("general_points", models.PositiveIntegerField(blank=True, null=True)),
                ("gender_points", models.PositiveIntegerField(blank=True, null=True)),
                ("category_points", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "classification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classification_results",
                        to="classifications.classification",
                    ),
                ),
                (
                    "runner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classification_results",
                        to="races.runner",
                    ),
                ),
            ],
            options={
                "ordering": ["general_points"],
            },
        ),
    ]
