# Generated by Django 4.2.2 on 2023-12-06 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classifications", "0002_classificationresult_club_points"),
    ]

    operations = [
        migrations.AddField(
            model_name="classification",
            name="slug",
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
    ]
