# Generated by Django 4.2.2 on 2023-12-07 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("classifications", "0003_classification_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="classificationresult",
            options={
                "ordering": ["general_points", "gender_points", "category_points"]
            },
        ),
    ]
