# Generated by Django 4.2.2 on 2023-11-02 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("race_versions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resultversion",
            name="club_points",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
